### ISSUE TITLE
EzVarChannel try to get the wrong channel

### ISSUE THREAD

**Issue by Lightjohn** [adufour/EzPlug#14]
Hi,

Just a report of the bug I found.
To create it:

```java
private EzVarSequence sequenceImg     = new EzVarSequence("Input Image");
private EzVarChannel  sequenceImgChan = new EzVarChannel("Image channel", sequenceImg.getVariable(), true);
```
And with some images it will crash on launch.

```
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:400)
    at java.util.ArrayList.get(ArrayList.java:413)
    at ome.xml.model.Pixels.getChannel(Pixels.java:573)
    at ome.xml.meta.OMEXMLMetadataImpl.getChannelName(OMEXMLMetadataImpl.java:1053)
    at icy.sequence.MetaDataUtil.getChannelName(MetaDataUtil.java:555)
    at icy.sequence.Sequence.getChannelName(Sequence.java:974)
    at plugins.adufour.vars.gui.swing.ChannelSelector$3$1.valueToString(ChannelSelector.java:93)
    at javax.swing.JFormattedTextField$AbstractFormatter.install(JFormattedTextField.java:949)
    at javax.swing.JFormattedTextField.setFormatter(JFormattedTextField.java:465)
    at javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:789)
    at javax.swing.JFormattedTextField.setValue(JFormattedTextField.java:502)
    at plugins.adufour.vars.gui.swing.ChannelSelector.updateInterfaceValue(ChannelSelector.java:126)
    at plugins.adufour.vars.gui.VarEditor.setEnabled(VarEditor.java:250)
    at plugins.adufour.ezplug.EzVar.addTo(EzVar.java:190)
    at plugins.adufour.ezplug.EzComponent$1.run(EzComponent.java:75)
    at icy.system.thread.ThreadUtil$CaughtRunnable.run(ThreadUtil.java:61)
    at icy.system.thread.ThreadUtil.invokeLater(ThreadUtil.java:261)
    at icy.system.thread.ThreadUtil.invokeLater(ThreadUtil.java:244)
    at plugins.adufour.ezplug.EzComponent.addToContainer(EzComponent.java:70)
    at plugins.adufour.ezplug.EzDialog.repack(EzDialog.java:289)
    at plugins.adufour.ezplug.EzDialog$1.run(EzDialog.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

From [Here](https://groups.google.com/forum/embed/?place=forum/icy-software&showsearch=true&showpopout=true&showtabs=false&parenturl=http%3A%2F%2Ficy.bioimageanalysis.org%2Fsupport#!topic/icy-software/PONfDU7N9l0)

**Comment by adufour** [comment]
Should now be fixed (as of 3.9.4). Could you double check (and re-open the issue if necessary?)
Thanks for the feedback!
